name: Release to PyPi and upload artifact

on:
  workflow_dispatch:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  release-package:
    name: Build and Publish Release Artifacts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493 #4.1.7
      - uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c #6.0.0
        name: Install Python
        with:
          python-version: '3.11'
      - name: Install Deps
        run: pip install -U twine==5.1.1 wheel==0.44.0
      - name: Build Artifacts
        run: |
          python setup.py sdist
          python setup.py bdist_wheel
        shell: bash
      - uses: actions/upload-artifact@89ef406dd8d7e03cfd12d9e0a4a378f454709029 #4.3.5
        with:
          path: ./dist/qiskit_ibm_catalog*
      - name: Publish to PyPi
        env:
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        run: twine upload dist/qiskit_ibm_catalog*
