name: Latest version tests

on:
  push:
    branches:
      - main
      - 'stable/**'
  pull_request:
    branches:
      - main
      - 'stable/**'
  schedule:
    - cron: '0 1 * * *'

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    strategy:
      max-parallel: 4
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.10', '3.11', '3.12', '3.13']
        include:
          - os: macos-latest
            python-version: 3.11
          # - os: windows-latest
          #   python-version: 3.11
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox
      - name: Modify tox.ini for more thorough check
        shell: bash
        run: |
          sed -i.bak -E '/#.*CI:[[:space:]]*skip-next-line/I{N;d;}' tox.ini
          cat tox.ini
      - name: Set tox environment name
        run: echo "TOXENV=py${{ matrix.python-version }}" >> $GITHUB_ENV
      - name: Test using tox environment
        run: tox -e $TOXENV
